// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Travel.WebApi.Models;

public partial class accommodation
{
    public int accommodation_id { get; set; }

    public string accommodation_name { get; set; }

    public DateOnly? checkin_date { get; set; }

    public DateOnly? checkout_date { get; set; }

    public string location { get; set; }
}