// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Travel.WebApi.Models;

public partial class article_repository
{
    public int article_repository_id { get; set; }

    public int? article_list_id { get; set; }

    public int? article_id { get; set; }

    public virtual article_overview article { get; set; }

    public virtual article_list article_list { get; set; }
}