// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Travel.WebApi.Models;

public partial class ArticleRepository
{
    public int ArticleRepositoryId { get; set; }

    public int? ArticleListId { get; set; }

    public int? ArticleId { get; set; }

    public virtual ArticleOverview Article { get; set; }

    public virtual ArticleList ArticleList { get; set; }
}