// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Travel.WebApi.Models;

public partial class article_list
{
    public int article_list_id { get; set; }

    public string article_list_name { get; set; }

    public int? memberunique_id { get; set; }

    public virtual ICollection<article_repository> article_repository { get; set; } = new List<article_repository>();

    public virtual basic_member_information memberunique { get; set; }
}