// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Travel.WebApi.Models;

public partial class article_picture
{
    public int article_pictures_id { get; set; }

    public int? article_id { get; set; }

    public byte[] article_pictures { get; set; }

    public string ArticlePicturesString { get; set; }

    public virtual article_overview article { get; set; }
}