// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Travel.WebApi.Models;

public partial class article_customization_list
{
    public int article_list_id { get; set; }

    public string article_list_name { get; set; }
}