// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Travel.WebApi.Models;

public partial class basic_commodity_information
{
    public int commodity_id { get; set; }

    public int? memberunique_id { get; set; }

    public string lover_nickname { get; set; }

    public string profession_id { get; set; }

    public string bodyshape_id { get; set; }

    public string gender { get; set; }

    public virtual bodyshape_table bodyshape { get; set; }

    public virtual basic_member_information memberunique { get; set; }

    public virtual ICollection<order> order { get; set; } = new List<order>();

    public virtual ICollection<product_datetime> product_datetime { get; set; } = new List<product_datetime>();

    public virtual profession_table profession { get; set; }
}