// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Travel.WebApi.Models;

public partial class basic_member_information
{
    public int memberunique_id { get; set; }

    public string member_name { get; set; }

    public bool? activate { get; set; }

    public string phone { get; set; }

    public DateTime? birthday { get; set; }

    public string email { get; set; }

    public string password { get; set; }

    public bool? be_commodity { get; set; }

    public int? level_id { get; set; }

    public decimal? member_value { get; set; }

    public int? followers { get; set; }

    public int? tracks { get; set; }

    public string introduction { get; set; }

    public string house_name { get; set; }

    public DateTime? house_createtime { get; set; }

    public DateTime? house_renewtime { get; set; }

    public byte[] member_picture { get; set; }

    public virtual ICollection<article_list> article_list { get; set; } = new List<article_list>();

    public virtual ICollection<article_overview> article_overview { get; set; } = new List<article_overview>();

    public virtual ICollection<basic_commodity_information> basic_commodity_information { get; set; } = new List<basic_commodity_information>();

    public virtual ICollection<comment> comment { get; set; } = new List<comment>();

    public virtual level_table level { get; set; }

    public virtual ICollection<mall_product_space> mall_product_space { get; set; } = new List<mall_product_space>();

    public virtual ICollection<members_like> members_like { get; set; } = new List<members_like>();

    public virtual ICollection<storedrecord> storedrecord { get; set; } = new List<storedrecord>();

    public virtual ICollection<tracklist> tracklist { get; set; } = new List<tracklist>();
}