// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Travel.WebApi.Models;

public partial class CommodityInteractive
{
    public int? CommodityId { get; set; }

    public string InteractiveId { get; set; }

    public virtual BasicCommodityInformation Commodity { get; set; }

    public virtual InteractiveTable Interactive { get; set; }
}