// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Travel.WebApi.Models;

public partial class commodity_picture
{
    public int? commodity_id { get; set; }

    public byte[] commodity_pictures { get; set; }

    public virtual basic_commodity_information commodity { get; set; }
}