// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Travel.WebApi.Models;

public partial class commodity_interest
{
    public int? commodity_id { get; set; }

    public string interest_id { get; set; }

    public virtual basic_commodity_information commodity { get; set; }

    public virtual interest_table_ interest { get; set; }
}