// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Travel.WebApi.Models;

public partial class CouponDiscountTable
{
    public string CoupondiscountId { get; set; }

    public DateTime? Expirationdate { get; set; }

    public decimal? Discountamount { get; set; }

    public virtual ICollection<Coupontable1> Coupontable1s { get; set; } = new List<Coupontable1>();
}