// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Travel.WebApi.Models;

public partial class coupon_table
{
    public int coupon_id { get; set; }

    public string couponame { get; set; }

    public string coupondiscount_id { get; set; }
}