// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Travel.WebApi.Models;

public partial class coupon_discount_table
{
    public string coupondiscount_id { get; set; }

    public DateTime? expirationdate { get; set; }

    public decimal? discountamount { get; set; }

    public virtual ICollection<coupontable> coupontable { get; set; } = new List<coupontable>();
}