// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Travel.WebApi.Models;

public partial class gold_exchange_table
{
    public int gold_denomination_id { get; set; }

    public string gold_denominatio_name { get; set; }

    public decimal? gold_amount { get; set; }

    public decimal? stored_amount { get; set; }

    public virtual ICollection<storedrecord> storedrecord { get; set; } = new List<storedrecord>();
}