// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Travel.WebApi.Models;

public partial class interest_table_
{
    public string interest_id { get; set; }

    public string interest_name { get; set; }
}