// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Travel.WebApi.Models;

public partial class interactive_table
{
    public string interactive_id { get; set; }

    public string interactive_name { get; set; }
}