// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Travel.WebApi.Models;

public partial class InterestTable
{
    public string InterestId { get; set; }

    public string InterestName { get; set; }
}