// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Travel.WebApi.Models;

public partial class LanguageTable
{
    public string LanguageId { get; set; }

    public string LanguageName { get; set; }
}