// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Travel.WebApi.Models;

public partial class level_table
{
    public int level_id { get; set; }

    public string level_name { get; set; }

    public double? discount { get; set; }

    public virtual ICollection<basic_member_information> basic_member_information { get; set; } = new List<basic_member_information>();
}