// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Travel.WebApi.Models;

public partial class mall_product_purchase_record
{
    public int mprecord_id { get; set; }

    public string member_name { get; set; }

    public int? mall_product_table_id { get; set; }

    public bool? exchange_status { get; set; }

    public DateTime? exchange_time { get; set; }

    public virtual mall_product_table mall_product_table { get; set; }
}