// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Travel.WebApi.Models;

public partial class mall_product_table
{
    public int mall_product_table_id { get; set; }

    public string mall_product_id { get; set; }

    public string mall_product_name { get; set; }

    public int? gold_amount { get; set; }

    public byte[] pimage { get; set; }

    public virtual ICollection<mall_product_purchase_record> mall_product_purchase_record { get; set; } = new List<mall_product_purchase_record>();

    public virtual ICollection<mall_product_space> mall_product_space { get; set; } = new List<mall_product_space>();

    public virtual ICollection<shoprecord_detail> shoprecord_detail { get; set; } = new List<shoprecord_detail>();
}