// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Travel.WebApi.Models;

public partial class members_like
{
    public int likes_id { get; set; }

    public int? article_id { get; set; }

    public int? memberunique_id { get; set; }

    public bool? likes { get; set; }

    public virtual article_overview article { get; set; }

    public virtual basic_member_information memberunique { get; set; }
}