// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Travel.WebApi.Models;

public partial class OfflineTypeTable
{
    public string OfflineTypeId { get; set; }

    public string OfflineTypeName { get; set; }
}