// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Travel.WebApi.Models;

public partial class offline_area_table
{
    public string area_id { get; set; }

    public string area_name { get; set; }
}