// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Travel.WebApi.Models;

public partial class online_type_table
{
    public string online_type_id { get; set; }

    public string online_type_name { get; set; }
}