// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Travel.WebApi.Models;

public partial class order
{
    public int order_id { get; set; }

    public int? commidity_id { get; set; }

    public int? memberunique_id { get; set; }

    public DateTime? create_time { get; set; }

    public double? discount { get; set; }

    public int? coupon_id { get; set; }

    public bool? paymentstatus { get; set; }

    public decimal? price_unfixed { get; set; }

    public decimal? price_fixed { get; set; }

    public virtual basic_commodity_information commidity { get; set; }
}