// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Travel.WebApi.Models;

public partial class product_travel
{
    public int travel_id { get; set; }

    public int? All_days { get; set; }

    public string travel_name { get; set; }

    public int? travelarea_id { get; set; }

    public DateTime? travel_datetime { get; set; }

    public string travel_introduction { get; set; }

    public string travel_meetingpoint { get; set; }

    public bool? product_show { get; set; }

    public decimal? price { get; set; }

    public string tag { get; set; }

    public string pictures { get; set; }

    public virtual ICollection<travel_details> travel_details { get; set; } = new List<travel_details>();

    public virtual travelarea_table travelarea { get; set; }

    public virtual ICollection<travelpictures_table> travelpictures_table { get; set; } = new List<travelpictures_table>();
}