// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Travel.WebApi.Models;

public partial class product_offline_topics
{
    public int downtopic_id { get; set; }

    public int? commidity_id { get; set; }

    public string dating_id { get; set; }

    public string offline_topics_name { get; set; }

    public string offline_type_id { get; set; }

    public string area_id { get; set; }

    public DateOnly? dating_date { get; set; }

    public TimeOnly? start_time { get; set; }

    public TimeOnly? end_time { get; set; }

    public decimal? price { get; set; }

    public bool? product_show { get; set; }
}