// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Travel.WebApi.Models;

public partial class product_online_topics
{
    public int uptopic_id { get; set; }

    public int? commidity_id { get; set; }

    public string dating_id { get; set; }

    public string online_topics_name { get; set; }

    public string online_type_id { get; set; }

    public DateOnly? dating_date { get; set; }

    public TimeOnly? start_time { get; set; }

    public TimeOnly? end_time { get; set; }

    public decimal? price { get; set; }

    public bool? product_show { get; set; }
}