// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Travel.WebApi.Models;

public partial class product_datetime
{
    public int notypedating_id { get; set; }

    public int commodity_id { get; set; }

    public string dating_id { get; set; }

    public DateOnly? datingdate { get; set; }

    public TimeOnly? startime { get; set; }

    public TimeOnly? endtime { get; set; }

    public decimal? price { get; set; }

    public bool? product_show { get; set; }

    public virtual basic_commodity_information commodity { get; set; }
}