// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Travel.WebApi.Models;

public partial class shoprecord
{
    public int shop_recordid { get; set; }

    public string member_name { get; set; }

    public bool? exchange_status { get; set; }

    public DateTime? purchase_time { get; set; }

    public int? total_price { get; set; }

    public string member_phone { get; set; }

    public string address { get; set; }

    public string shoporderid { get; set; }

    public virtual ICollection<shoprecord_detail> shoprecord_detail { get; set; } = new List<shoprecord_detail>();
}