// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Travel.WebApi.Models;

public partial class shoprecord_detail
{
    public int shoprecord_detailid { get; set; }

    public int? shop_recordid { get; set; }

    public int? mall_product_table_id { get; set; }

    public string mall_product_name { get; set; }

    public int? mall_product_quantity { get; set; }

    public string shoporderid { get; set; }

    public virtual mall_product_table mall_product_table { get; set; }

    public virtual shoprecord shop_record { get; set; }
}