// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Travel.WebApi.Models;

public partial class storedrecord
{
    public int store_record_id { get; set; }

    public int? memberunique_id { get; set; }

    public int? gold_denomination_id { get; set; }

    public DateTime? purchase_date { get; set; }

    public bool? payment_status { get; set; }

    public bool? refund_status { get; set; }

    public virtual gold_exchange_table gold_denomination { get; set; }

    public virtual basic_member_information memberunique { get; set; }
}