// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Travel.WebApi.Models;

public partial class Tracklist
{
    public int TracklistId { get; set; }

    public int? MemberuniqueId { get; set; }

    public int? TrackMemberId { get; set; }

    public virtual BasicMemberInformation Memberunique { get; set; }
}