// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Travel.WebApi.Models;

public partial class TravelpicturesTable
{
    public int PictureId { get; set; }

    public int? TravelId { get; set; }

    public byte[] TravelPicture { get; set; }

    public virtual ProductTravel Travel { get; set; }
}