// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Travel.WebApi.Models;

public partial class travelpictures_table
{
    public int picture_id { get; set; }

    public int? travel_id { get; set; }

    public byte[] travel_picture { get; set; }

    public virtual product_travel travel { get; set; }
}