// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Travel.WebApi.Models;

public partial class travel_details
{
    public int travel_details_id { get; set; }

    public int? travel_id { get; set; }

    public string travel_detailed_introduction { get; set; }

    public bool? tour_bus { get; set; }

    public bool? bus { get; set; }

    public bool? train { get; set; }

    public string morning_Name { get; set; }

    public string lunch_Name { get; set; }

    public string dinner_Name { get; set; }

    public string accommodation_Name { get; set; }

    public int? which_day { get; set; }

    public virtual product_travel travel { get; set; }
}