// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Travel.WebApi.Models;

public partial class travel_transportation_table
{
    public bool transportation_id { get; set; }

    public string transport_mode { get; set; }

    public DateOnly? departure_date { get; set; }

    public DateOnly? arrival_date { get; set; }
}