// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Travel.WebApi.Models;

public partial class travelarea_table
{
    public int travelarea_id { get; set; }

    public string travelarea_name { get; set; }

    public virtual ICollection<product_travel> product_travel { get; set; } = new List<product_travel>();
}